### ISSUE TITLE
Nuget and .net core support

### ISSUE THREAD

**Issue by danbopes** [Warpten/DBClientFiles.NET#16]
Is this possible?

**Comment by Warpten** [comment]
I'm not sure what you mean because this is already all a .NET Core project (except maybe non-essential projects, like bench or unit tests. As far as Nuget is done, I'll consider it if I ever get to not be burnt out before finishing supporting all major DB2 versions

**Comment by Warpten** [comment]
In the meantime, if you want anything but WDC2/3, use [http://github.com/Warpten/DBFilesClient.NET](`DBFilesClient.NET`). It's on Nuget.
